@startuml
autonumber
actor "Utente" as GC

activate GC

GC -> "<<System (C4)>> SPA/Frontend" : Iniciar o processo de requsisitar tarefa
activate "<<System (C4)>> SPA/Frontend"
"<<System (C4)>> SPA/Frontend"  --> GC : Solicitar os dados necessário
deactivate "<<System (C4)>> SPA/Frontend"
GC -> "<<System (C4)>> SPA/Frontend"  : Introduzir os dados solicitados
activate "<<System (C4)>> SPA/Frontend"

"<<System (C4)>> SPA/Frontend"  --> GC : Informa o sucesso da operação
deactivate "<<System (C4)>> SPA/Frontend"

deactivate GC

@enduml
