@startuml
autonumber
actor "Utente" as GC
participant "<<System (C4)>> \n SPA/Frontend"  as UI
participant "<<System (C4)>>\n MDC" as MDC

activate GC


GC -> UI : Iniciar o processo de requisitar tarefa
activate UI
UI--> GC : Solicitar os dados necessário
deactivate UI
GC -> UI: Introduzir os dados solicitados
activate UI
UI -> MDC : POST Task
activate MDC
MDC -> MDC : create(task)
MDC --> UI : Task criado
UI --> GC : Informa o sucesso da operação
deactivate UI

deactivate GC

@enduml
