@startuml
autonumber
actor "Gestor de Campus" as GC

participant "<<System (C4)>>\n RobDroneGo" as SPA

activate GC

GC -> SPA : Iniciar o processo de edição de um piso
activate SPA
SPA --> GC : Seleccionar o piso que deseja editar e introduzir os dados relativos ao mesmo
deactivate SPA

GC -> SPA : Seleccionar e inserir os dados solicitados
activate SPA
SPA --> GC : Solicitar a confirmação dos dados inseridos 
deactivate SPA

GC -> SPA : Confirmar os dados
activate SPA
SPA --> GC : Informar do sucesso da operação 
deactivate SPA

deactivate GC

@enduml