@startuml
autonumber
actor "Gestor de Campus" as GC

participant "<<System (C4)>>\n SPA/Frontend" as UI
participant "<<System (C4)>>\n MDC" as MDC

GC -> UI : faz pedido para criacao da passagem 

UI --> GC: solicita os dados para criar passagem

GC -> UI : envia os dados para criar a passagem 

UI -> MDC : createBridge(idBridge, positionX, positionY, positionX, positionY, buildingY, floorY, buildingX, floorX)

MDC --> UI : bridge

UI --> GC: passagem criada com sucesso



@enduml