@startuml
autonumber
actor "Fleet Manager" as GC
participant "<<System (C4)>>\n SPA/Frontend" as UI
participant "<<System (C4)>>\n MDC" as MDC

activate GC


GC -> UI : Initiate process to inhibit robot
activate UI
UI--> GC : lists all robots US380
deactivate UI
GC -> UI: Selects Robot to inhibit
activate UI
UI -> MDC : PATCH Robot
activate MDC
MDC -> MDC : edit(robot)
MDC --> UI : robot inhibited
UI --> GC : Informs of operation success or failure
deactivate UI

deactivate GC

@enduml