@startuml

actor "Gestor de Tarefas"

' Referência ao diagrama anterior
note over "Gestor de Tarefas"
  ver Diagrama LogInN2(representa interaçao anterior)
end note

"Gestor de Tarefas" -> "<<System (C4)>> \n SPA/Frontend" : faz pedido para listar tarefas pendentes de aprovacao

"<<System (C4)>> \n SPA/Frontend" -> "<<System (C4)>>\n MDT": GET '/Tasks/Pending'

"<<System (C4)>>\n MDT" --> "<<System (C4)>> \n SPA/Frontend": return lista de tarefas pendentes de aprovacao

"<<System (C4)>> \n SPA/Frontend" --> "Gestor de Tarefas" : mostra a lista de tarefas pendentes de aprovacao

@enduml